# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff9d7462dd9941ef6e5ca68d9d620e1871751a0e91501a50e0033644d7b4b2b4c585af29a375582c9dd47584bac6dcd7fd4cc6abbc25d2775ba0248501927b73

test:
  secret_key_base: 2009bcbcaea03179a43df3ae2d29d6e06949510c5114fd2f0ddda315f6bfb5b31aadcd18e987f0a25d7dfa71ea81434ef61194b7e3d47498199be2535d2cf3c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
